"""Agregar campo name a items

Revision ID: 15c26e05cb3a
Revises: 08180b24195b
Create Date: 2025-10-14 22:57:03.466415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c26e05cb3a'
down_revision: Union[str, Sequence[str], None] = '08180b24195b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_ticket')
    op.drop_table('price_lists')
    op.drop_table('clients')
    op.drop_table('items_price_list')
    op.drop_table('tickets')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('state', sa.VARCHAR(length=6), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_price_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['price_lists.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('adress', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.Column('unitPrice', sa.FLOAT(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('itemPriceList_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['itemPriceList_id'], ['items_price_list.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
